spring:
  datasource:
    url: jdbc:mysql://${DB_url}:${DB_port}/${DB_dataBaseName}
    username: ${DB_username}
    password: ${DB_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # 로컬에서만 update 옵션 사용하기
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.sql: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml