spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: HaewoosoDB
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.sql: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml