name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: rlaxodnr457/haewooso
          stage: main
          yaml: |
            name: haewooso-backend
            app: java@17
            options:
              ports: 8080
              env:
                - name: DB_url
                  value: svc.sel4.cloudtype.app
                - name: DB_port
                  value: "30831"
                - name: DB_username
                  value: root
                - name: DB_password
                  value: HaewoosoDB
                - name: DB_dataBaseName
                  value: haewooso
                - name: FCMSDK
                  value: {"type":"service_account","project_id":"haewooso","private_key_id":"b5fdea6348c08a3df6f75fc6814cd7a55e15da1d","private_key":"-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDDDyzu+yZ/LBwV\nuE3/ZnnX4RALRgp1Z6/dK9BdS4FGGNMceBSq7ZSfIQS8s6l1vRnCLkGkH9buBP3Z\nsxSFkCpQj+g8ct1vuzNYNkaFNzqK1OajnyfKE1p5pvK6tTyFUIiWosVUaon0bDwD\nyQaI7KCVbBP2pvuoL8q0WGVeXpF3GAASdQxlq+9oVQhQCWaW0t/UrbWwFe04Jgfn\nVLnhjYDyQT+jgDGCjn3busZnA8XXMmzrVpg/uoXAZ48WtTZ6z5qHayKz9gi4khMj\nqPn33ZNyTf8QXBVFWrbnpm8dyNRAyYC96xn5ebjhiVZag8zFlnK6xtPq/mTXus6/\ndTwvydN9AgMBAAECggEAAVcwnB4yRB6nEm157cGEILFy39z18/DH6Dl68l/d43/c\nAulUB7O1I93Wej8y24oL7AYk3IOn1sAb3YaUo3Fbn8JJb+brMi94xB2wC44sXb67\nrLq1Njc+qzDe9ge1AtvhlcVzHT1+irqWtAD08Ep4tRDb10QLspAiMMNIbmcF0Wof\n/afC/+68hBkkT14XGvR9I7XfCuXtIcn1+78oQTicJHJyA8duuSTuJz5ky1rwfw2N\nwGygkw8b0p/1RXZRUx35wFup3VmMhBoGNJGb3DrrSStZ+Q0Ahg3anRMSYdOXyecW\nwmzOH297SQVpc/tXUe9aKdFKu3KanTsuTDyVTq0McQKBgQDgqUyVYVxxkNUZMU/g\nJ7im2ZDIc5PfwNhl4oXyKTfExdYXLfJ7fiKkaciFQNt/fN1fmarNFJb743yPOMSv\nMpyL4HCydWjlzvChDQeaES2xxFv/ElJDZURVB61EfWdvXdKG2mAYyvNRSsDr5FAf\n/FavcD+Y5p/I3QBy3CFD4xh7MQKBgQDeRMgKEKIHMgQ5qjg88oe4gy6vszgBmPkr\nxq56NSramIwM0DzD8iV8zD3reA7gquqkd/ZYNL6IKtBAL0JySij/Bai0WHYBJs0t\nW76jZBbLIavSMzHMumiCmK4285ClERJa1Yi0OKYbhYZz/q2zi1d7xTmrCawz99At\nVENSADwyDQKBgArcJDeUXUOgHKz7FUFgqixml/kYnS1TxSInsRHjrC524cJ9Fhui\nHUqVUnwehn3DK3BTnU4MkL/cX0kNFXTinW6lis0Vn9x8BGXEm3l3Gx5cv5W07QUV\nABicJmQJK9bWUjbyl3KbXOexFWJRxw3ExOv2IRzjCRZMmJj0yybc83IBAoGAc2tk\nNVXNzc67QvaRnZSTxczZQYPfYXT+by0NDYjuZ/UvRLgd1eK4dMXaoZwGncQjdKSW\n19cL2cnhunLQHmlEQKm/oWcOYCq2AQfTRyWCcJlbkBvlkFp8StTeIsr4Ib9ruJ+K\nDYwdNc1wtGtb6BBDrZINEDRFp/bXs7I+Ayb8G0ECgYBK+eVBdH2LOmhlFsrcmbxH\nkolSjYiORdaBqqyGiacp3nC/tnGnbrmZjoQCeSFbsaCo+AfUJGg48CzuDy4xEoCg\n1ryO/BsMGTB0uqgPXppe8CfRlaIkyzIdVuscE26UnViUjXpUn7R4S0nBrKXaRa9i\nfMu2VDmNdOK3PSsisNhCEQ==\n-----END PRIVATE KEY-----\n","client_email":"firebase-adminsdk-r1plg@haewooso.iam.gserviceaccount.com","client_id":"100797656690912312212","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-r1plg%40haewooso.iam.gserviceaccount.com","universe_domain":"googleapis.com"}
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: java-springboot
        
